---
- hosts: webservers
  user: vagrant
  become: yes

  tasks:
    - name: Copy README to remote
      copy:
        src: ./README.wsl2.txt
        dest: /tmp/README.txt
        owner: root
   
    - name: yum Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: apt Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: Start service apache2, if not started
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: Insert tcp/80 a rule on line 1
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        action: insert
        rule_num: 1
