---
- hosts: webservers
  user: vagrant
  become: yes

  tasks:
    - name: Copy README to remote
      copy:
        src: "{{ item }}"
        dest: /tmp/
        owner: root

      with_fileglob:
        - files/*.pub
