---
- hosts: webservers
  user: vagrant
  become: yes

  tasks:
    - name: index.html template
      ansible.builtin.template:
        src: ./templates/index.html.j2
        dest: /var/www/html/index.html
